version: "3.8"

services:
  postgres_crud:
    image: postgres:13.1-alpine
    container_name: postgres_crud
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=sua-senha
         - POSTGRES_USER=postgres
         - POSTGRES_DB=crud_springboot
    networks:
      - crud-network
    
  crud_springboot:
    image: crud_springboot:0.1
    build:
      context: crud/
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_crud:5432/crud_springboot
    depends_on:
      - postgres_crud
    container_name: crud_springboot
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - crud-network
    
volumes:
  postgres-data:
  
networks:
  crud-network:
    driver: bridge
    
# docker compose up -d
