# Etapa única: ambiente de desenvolvimento
FROM node:18

# Diretório de trabalho
WORKDIR /app

# Copiar apenas arquivos de dependência primeiro
COPY package.json package-lock.json ./

# Instalar as dependências
RUN npm install -g @angular/cli@14.2.13 && npm install

# Copiar todo o restante do código
COPY . .

# Expor a porta padrão do Angular
EXPOSE 4200

# Comando padrão: iniciar o ng serve
CMD ["npm", "run", "start"]
