version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    container_name: frontend-angular-produtos
    restart: unless-stopped

# docker compose up -d
