version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend-angular-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start -- --host 0.0.0.0 --port 4200 --disable-host-check

# docker-compose -f docker-compose.dev.yml up --build -d